server:
  port: 8080

zuul:
  ignoredServices: '*'
  routes:
    orangebox-storage:
      path: /storage/**
      serviceId: orb-storage
    orangebox-trading:
          path: /trading/**
          serviceId: orb-trading

eureka:
  client:
    serviceUrl:
      defaultZone: ${ORANGEBOX_SERVICE_LOCATOR_SERVER_URI:http://localhost:8761/eureka/}
      
      
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}