spring:
  profiles:
    active: heroku
    include: postgres
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create


eureka:
  instance:
    hostname: ${DOMAIN_NAME}
  password: ${USER_PASSWORD:password}